server:
  port: 9999
  tomcat:
    max-connections: 1000
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1024 #byte

spring:
  application:
    name: springboot-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/trace?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&relaxAutoCommit=true&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root



logging:
  level:
    warn: info
    a.b.c: info
    a.b.c.exchange.utils.HttpClient: warn
    a.b.c.trace.component.socket.MyWebSocketClient: warn
    a.b.c.trace.component.socket.SocketClient.SocketClient: warn
