#./filebeat -e -c /app/filebeat/filebeatest.yml -d "publish"
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /opt/logs/lion/8900/cx-sport-app-service.json
output.kafka:
  enabled: true
  hosts: ["127.0.0.1:9092"]
  topic: filebeat_log