CREATE TABLE  book (
  id BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `book_name` VARCHAR(100)  NOT NULL COMMENT '书名',
  `isbn` VARCHAR(100)  NOT NULL COMMENT 'isbn',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
)  COMMENT='图书表';
